<?php
/**
 * Copy Custom Options.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magento Team
 * that is bundled with this package of Medma Infomatix Pvt. Ltd.
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Medma Support does not guarantee correct work of this package
 * on any other Magento edition except Magento COMMUNITY edition.
 * =================================================================
**/
?>
<?php
$withOptions	=	$this->_getCollectionWithOptions();
$withOutCoptions 	=	$this->_getCollectionWithoutOptions();
?>

<!-- delete custom options -->
<div class="main-col-copy-options">
<form name="delete_options_form" method="post" action="<?php echo $this->getDeleteUrl()?>">
<input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
<div class="content-header">
<table cellspacing="0">
    <tr>
        <td class="del_row">
        	<h3 class="icon-head head-products">
        		<?php echo $this->__('Delete Custom Options');?>
        	</h3>
        </td>
 <td class="a-right">
		<p>
			<button  title="Delete Custom Options" type="submit"  class="scalable " style=""><span><span><span><?php echo $this->__('Delete Selected Custom Options');?></span></span></span></button>

			</p>        
	</td>
       
    </tr>
</table>
</div>

<div class="box">
      <div class="entry-edit">
                <div class="entry-edit-head">
                    <strong><?php echo $this->__('Delete Custom Options');?>
           					<?php echo $this->__('(selected custom options will be deleted)');?></strong>
                </div>
        <div class="fieldset copy-options">
		<table class="form-list" cellspacing="0">
      <tbody>
      <?php if(count($withOptions->getData())<=0):?>
      	<tr>
					<td colspan = "3" class="value"><?php echo $this->__('There are no products with custom options.')?></td>							
					</tr>
			<?php else : $i=0;?>
			<?php foreach($this->_getCollectionWithOptions() as $_product): ?>
					<?php $_product->load(); ?>
					<?php if(count($_product->getOptions())): ?>
					<tr>
					<td class="value"><?php echo $_product->getName().'&nbsp;('.$_product->getSku().')';?></td>
						<!-- display all custom options of products -->
						<td class="value grid">
									<table cellspacing="0" class="data border" id="group_prices_table">
                		<colgroup>
										<col>
										<col>
										<col width="1">
										</colgroup><thead>
												<tr class="headings">
												    <th><?php echo $this->__('Action'); ?></th>												    
												    <th class="last"><?php echo $this->__('Options'); ?></th>
												</tr>
										</thead>
										<tbody>
												<?php 
												 foreach ($_product->getOptions() as $o):?>
													<tr>
														 <td ><input class="option_<?php echo $i?>" type="checkbox" name="options[<?php echo $_product->getId()?>][]" value="<?php echo $o->getId()?>"></td>
												    <td colspan="4" class="a-left"><?php echo $o->getTitle();?></td>										   
												</tr>
												<?php endforeach; ?>
										</tbody>
										<tfoot>
												<tr>
												    <td></td>
												    <td colspan="4" class="a-right">
																<input type="hidden" name="option_<?php echo $i?>" id="option_<?php echo $i?>" value="0">
																<button title="Select Options" onclick="selectAllCheckbox('option_<?php echo $i?>')" id="selectAll_<?php echo $i ?>" type="button" class="scalable">
																		<span><span><span><?php echo $this->__('Select / Deselect')?></span></span></span>	
																</button>
														</td>
												</tr>
										</tfoot>
								</table>
						</td> 
						<!-- display of custom options of products ends-->			
					</tr>
					<?php $i++; endif; ?>
			<?php endforeach; ?>
			<?php endif; ?>
		</tbody>
		</table>
		
        </div>
    </div>
</div>
</form>
</div>
<!-- delete custom option ends -->

